exclude: [".gitignore", "readme.md", "Gemfile", "Gemfile.lock"]
gems: [jekyll-paginate,jekyll-sitemap]

# Setup
title:            Griffio
author:
  name:           'GRIFFIO'
  url:            'https://github.com/griffio'
baseurl:          /
paginate:         19

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/griffio
