exclude: [".gitignore", "readme.md", "Gemfile", "Gemfile.lock"]
gems: [jekyll-paginate,jekyll-sitemap]

# Setup
author:         griffio
baseurl:
url:            https://griffio.github.com
github:         https://github.com/griffio
name:           griffio
repo:           https://github.com/griffio/griffio.github.io
title:          Griffio
paginate:       25
version:        1.1.0


