auto: true
exclude: [".gitignore", "readme.md", "Gemfile", "Gemfile.lock"]
gems:
  - jekyll-sitemap

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Griffio
author:
  name:           'GRIFFIO'
  url:            'https://github.com/griffio'
baseurl:          /
paginate:         15

# Custom vars
version:          0.1.0

github:
  repo:           https://github.com/griffio
